// 30 camping gear items available for rent in Vancouver, BC.
// All rates in CAD. Weekly = ~5x daily, Monthly = ~16x daily.
window.PRODUCTS = [
  // ---------------- Shelter ----------------
  { id: 1,  category: "Shelter", icon: "⛺", color: "#1f3d2c", fg: "#d6e553",
    name: "MSR Hubba Hubba — 2P Backpacking Tent",
    desc: "Featherweight freestanding tent. Two doors, two vestibules, packs to 2.4kg.",
    daily: 28, weekly: 140, monthly: 440 },
  { id: 2,  category: "Shelter", icon: "🏕️", color: "#e8623d", fg: "#fff",
    name: "REI Wonderland — 4P Family Tent",
    desc: "Stand-up height, big mesh windows. Perfect for car camping at Porteau Cove.",
    daily: 38, weekly: 190, monthly: 600 },
  { id: 3,  category: "Shelter", icon: "🏠", color: "#2b6e8a", fg: "#fff",
    name: "Coleman Octagon — 6P Cabin Tent",
    desc: "Whole-crew shelter for Cultus Lake or Golden Ears. Massive 12'x12' floor.",
    daily: 48, weekly: 240, monthly: 760 },
  { id: 4,  category: "Shelter", icon: "🛖", color: "#f1d8b8", fg: "#15201a",
    name: "Big Agnes Tarp Shelter — 10x10",
    desc: "Stand-alone tarp + 4 poles. Keeps the BC drizzle off the picnic table.",
    daily: 18, weekly: 90, monthly: 280 },

  // ---------------- Sleep ----------------
  { id: 5,  category: "Sleep", icon: "🛌", color: "#15201a", fg: "#d6e553",
    name: "Western Mountaineering Down Bag · -10°C",
    desc: "850-fill goose down. Toasty for shoulder-season alpine trips.",
    daily: 22, weekly: 110, monthly: 350 },
  { id: 6,  category: "Sleep", icon: "💤", color: "#d6e553", fg: "#15201a",
    name: "MEC Synthetic Sleeping Bag · 0°C",
    desc: "Stays warm wet — ideal for damp coastal nights.",
    daily: 16, weekly: 80, monthly: 250 },
  { id: 7,  category: "Sleep", icon: "🟦", color: "#2b6e8a", fg: "#fff",
    name: "Therm-a-Rest NeoAir Inflatable Pad",
    desc: "R-value 4.5, packs to a water-bottle size. Two-minute inflate.",
    daily: 12, weekly: 60, monthly: 190 },
  { id: 8,  category: "Sleep", icon: "🛏️", color: "#e8623d", fg: "#fff",
    name: "Exped MegaMat — Double Sleeping Pad",
    desc: "10cm of cushion for two. Car-camping luxury.",
    daily: 24, weekly: 120, monthly: 380 },
  { id: 9,  category: "Sleep", icon: "🌙", color: "#1f3d2c", fg: "#fff",
    name: "Sea to Summit Camp Pillow",
    desc: "Plush stretch knit, packs to a fist. Pair with any pad.",
    daily: 6, weekly: 30, monthly: 90 },

  // ---------------- Packs ----------------
  { id: 10, category: "Packs", icon: "🎒", color: "#d6e553", fg: "#15201a",
    name: "Osprey Atmos AG 65 — Multi-Day Pack",
    desc: "Anti-gravity suspension, fits 5-10 day trips. Sized M.",
    daily: 18, weekly: 90, monthly: 280 },
  { id: 11, category: "Packs", icon: "🥾", color: "#1f3d2c", fg: "#d6e553",
    name: "Deuter Speed Lite 30 — Daypack",
    desc: "Slim 30L for fast hikes — Lions, St. Mark's, Garibaldi day-trips.",
    daily: 10, weekly: 50, monthly: 160 },
  { id: 12, category: "Packs", icon: "🧗", color: "#e8623d", fg: "#fff",
    name: "Black Diamond 45L Alpine Pack",
    desc: "Stripped-down for fast-and-light overnight missions.",
    daily: 14, weekly: 70, monthly: 220 },

  // ---------------- Cooking ----------------
  { id: 13, category: "Cooking", icon: "🔥", color: "#e8623d", fg: "#fff",
    name: "Coleman Triton — 2-Burner Stove",
    desc: "Classic propane 2-burner. Bombproof for any campsite.",
    daily: 14, weekly: 70, monthly: 220 },
  { id: 14, category: "Cooking", icon: "♨️", color: "#15201a", fg: "#e8623d",
    name: "MSR PocketRocket 2 — Backpacking Stove",
    desc: "73g of pure flame. Boils 1L in 3.5 min.",
    daily: 8, weekly: 40, monthly: 130 },
  { id: 15, category: "Cooking", icon: "🍳", color: "#2b6e8a", fg: "#fff",
    name: "GSI Pinnacle 4-Person Cook Set",
    desc: "Pots, pans, plates, mugs — nests into one bag.",
    daily: 12, weekly: 60, monthly: 190 },
  { id: 16, category: "Cooking", icon: "☕", color: "#f1d8b8", fg: "#15201a",
    name: "GSI Java Press — Camp French Press",
    desc: "Because real coffee is non-negotiable. 30oz insulated.",
    daily: 6, weekly: 30, monthly: 90 },
  { id: 17, category: "Cooking", icon: "🧊", color: "#2b6e8a", fg: "#fff",
    name: "YETI Tundra 45 — Hard Cooler",
    desc: "Ice for 5+ days. Bear-resistant when locked.",
    daily: 18, weekly: 90, monthly: 280 },
  { id: 18, category: "Cooking", icon: "🥡", color: "#d6e553", fg: "#15201a",
    name: "IceMule 25L Soft Cooler",
    desc: "Pack-on-your-back cooler for paddle trips.",
    daily: 10, weekly: 50, monthly: 160 },

  // ---------------- Light & Power ----------------
  { id: 19, category: "Light & Power", icon: "💡", color: "#15201a", fg: "#d6e553",
    name: "Black Diamond Spot 400 — Headlamp",
    desc: "400 lumens, IPX8 waterproof. Hands-free for camp tasks.",
    daily: 6, weekly: 30, monthly: 90 },
  { id: 20, category: "Light & Power", icon: "🏮", color: "#e8623d", fg: "#fff",
    name: "Goal Zero Lighthouse 600 — Lantern",
    desc: "USB rechargeable, doubles as a power bank.",
    daily: 10, weekly: 50, monthly: 160 },
  { id: 21, category: "Light & Power", icon: "🔋", color: "#1f3d2c", fg: "#d6e553",
    name: "Goal Zero Yeti 200X — Power Station",
    desc: "187Wh battery for phones, drones, CPAPs. Solar-ready.",
    daily: 24, weekly: 120, monthly: 380 },

  // ---------------- Navigation & Safety ----------------
  { id: 22, category: "Navigation & Safety", icon: "🧭", color: "#2b6e8a", fg: "#fff",
    name: "Garmin GPSMAP 67 — Handheld GPS",
    desc: "Preloaded BC topo maps. Battery for 180 hours.",
    daily: 14, weekly: 70, monthly: 220 },
  { id: 23, category: "Navigation & Safety", icon: "📡", color: "#e8623d", fg: "#fff",
    name: "Garmin inReach Mini 2 — Satellite Comm",
    desc: "Two-way satellite messaging + SOS. Coverage anywhere.",
    daily: 16, weekly: 80, monthly: 250 },
  { id: 24, category: "Navigation & Safety", icon: "🐻", color: "#1f3d2c", fg: "#fff",
    name: "Counter Assault Bear Spray + Holster",
    desc: "Mandatory for backcountry BC. Comes fresh, never expired.",
    daily: 8, weekly: 40, monthly: 130 },
  { id: 25, category: "Navigation & Safety", icon: "🥫", color: "#d6e553", fg: "#15201a",
    name: "BearVault BV500 — Bear Canister",
    desc: "Required at most BC backcountry sites. 11.5L volume.",
    daily: 8, weekly: 40, monthly: 130 },

  // ---------------- Water ----------------
  { id: 26, category: "Water", icon: "💧", color: "#2b6e8a", fg: "#fff",
    name: "Katadyn BeFree — Squeeze Filter (1L)",
    desc: "Filter on the move. 0.1 micron, no pumping.",
    daily: 6, weekly: 30, monthly: 90 },
  { id: 27, category: "Water", icon: "🚰", color: "#15201a", fg: "#d6e553",
    name: "Platypus GravityWorks — 4L Filter",
    desc: "Group water in minutes. No pumping, just gravity.",
    daily: 10, weekly: 50, monthly: 160 },

  // ---------------- Camp Comfort ----------------
  { id: 28, category: "Camp Comfort", icon: "🪑", color: "#f1d8b8", fg: "#15201a",
    name: "Helinox Chair One — Camp Chair",
    desc: "960g packable chair. Fits in your daypack.",
    daily: 6, weekly: 30, monthly: 90 },
  { id: 29, category: "Camp Comfort", icon: "🪵", color: "#1f3d2c", fg: "#d6e553",
    name: "ALPS Mountaineering Camp Table",
    desc: "Roll-top aluminum table. Seats four for dinner.",
    daily: 8, weekly: 40, monthly: 130 },
  { id: 30, category: "Camp Comfort", icon: "🌴", color: "#d6e553", fg: "#15201a",
    name: "ENO DoubleNest + Bug Net Hammock Kit",
    desc: "Two-person hammock, straps and bug net. Mosquito-proof naps.",
    daily: 10, weekly: 50, monthly: 160 },
];
